# configuration file for automatic issue branch creation
branchName: '${issue.number}-${issue.title}'
silent: true
autoCloseIssue: true
gitSafeReplacementChar: '-'

branches:
  - label: question
    skip: true